### ISSUE TITLE
M1 Reflection - Things that can be improved in future Milestone

### ISSUE THREAD

**Issue by sh-how** [CRMNLS/INF-2001-Project#47]
Discuss and summarize in group on what are the things that can be improved in future milestone?

**Comment by Shadowtailx** [comment]
Based on the team's M1 Feedback, there are a few points that could have been done better.

In particular, the use case diagram could have been done better. In M1, the team emphasised more on the clarity when we were designing the use case diagram. This resulted in the team's decision to simplify the diagram (i.e. Manage Account instead of breaking it down into its respective create, read, update, delete component). This caused an underestimation of use cases in our diagram. Additionally, the use case description was not detailed enough, and did not start with the primary actor. This resulted in the low number of transactions per use case. As a result, the estimation process were affected.

In M2, the team will update the use case diagram and use case description to be more detailed to provide a better representation of the system.
